"""
aurem_db_client.py — SDK generated by AUREM CTO's Personal Track scaffolder.

Talks to AUREM's managed shared MongoDB via a scoped REST API instead
of a raw connection string. This means the generated app NEVER has
raw DB credentials baked into its code — safer to open-source, safer
to hand off, and the Personal Track migration path (Phase 5, dedicated
Supabase) can swap the transport later without touching your app code.

Config (in .env):
    AUREM_API_BASE      = https://api.auremcto.com
    AUREM_APP_ID        = pt_xxxxxxxx (unique to your project — auto-injected)
    AUREM_APP_TOKEN     = eyJ... (JWT minted by AUREM for your app's user session)

Usage:
    from aurem_db_client import AuremDB
    db = AuremDB()
    todo = await db.collection("todos").insert({"title": "Ship it"})
    all_todos = await db.collection("todos").find({})
"""
import os
from typing import Any, Optional

import httpx


class _Collection:
    def __init__(self, client: "AuremDB", name: str):
        self._c = client
        self.name = name

    async def find(self, filter: Optional[dict] = None, limit: int = 50,
                   sort: Optional[list] = None) -> list[dict]:
        r = await self._c._post(
            f"{self.name}/find",
            {"filter": filter or {}, "limit": limit, "sort": sort},
        )
        return (r or {}).get("docs", [])

    async def find_one(self, filter: dict) -> Optional[dict]:
        r = await self._c._post(f"{self.name}/find-one", {"filter": filter})
        return (r or {}).get("doc")

    async def insert(self, data: dict, schema: Optional[dict] = None) -> dict:
        return await self._c._post(f"{self.name}/insert",
                                   {"data": data, "schema": schema})

    async def update(self, filter: dict, patch: dict) -> dict:
        return await self._c._request(
            "PATCH", f"{self.name}/update",
            {"filter": filter, "patch": patch},
        )

    async def delete(self, doc_id: str) -> dict:
        return await self._c._request("DELETE", f"{self.name}/{doc_id}", None)


class AuremDB:
    def __init__(self) -> None:
        self._base = os.environ["AUREM_API_BASE"].rstrip("/")
        self._app_id = os.environ["AUREM_APP_ID"]
        self._token  = os.environ["AUREM_APP_TOKEN"]

    def collection(self, name: str) -> _Collection:
        return _Collection(self, name)

    async def _post(self, path: str, body: Any) -> dict:
        return await self._request("POST", path, body)

    async def _request(self, method: str, path: str, body: Any) -> dict:
        url = f"{self._base}/api/aurem-dev/managed-db/{self._app_id}/{path}"
        async with httpx.AsyncClient(timeout=15.0) as cli:
            if method == "GET":
                r = await cli.get(url, headers=self._headers())
            elif method == "DELETE":
                r = await cli.delete(url, headers=self._headers())
            else:
                r = await cli.request(method, url, headers=self._headers(),
                                      json=body)
        if r.status_code >= 400:
            raise RuntimeError(f"AuremDB {method} {path} → HTTP {r.status_code}: {r.text[:200]}")
        return r.json() if r.text else {}

    def _headers(self) -> dict:
        return {"Authorization": f"Bearer {self._token}",
                "Content-Type": "application/json"}
