"""
auth.py — Production-ready email/password auth for Personal Track apps.

Generated by AUREM CTO's Personal Track scaffolder.  Iter 212m-238
security hardening pass:

    ✅ httpOnly + Secure + SameSite=Lax cookies      (no localStorage — XSS-safe)
    ✅ Short-lived access token (1h) + refresh (30d) (rotation on every refresh)
    ✅ bcrypt-12 password hashing
    ✅ Sliding-window per-IP rate limits on all sensitive endpoints
    ✅ Enumeration-safe password-reset flow (15-min token, body-only, generic message)
    ✅ Constant-time password compare via bcrypt.checkpw

Endpoints:
    POST /api/auth/signup                 → sets cookies
    POST /api/auth/login                  → sets cookies
    POST /api/auth/refresh                → rotates cookies
    POST /api/auth/logout                 → clears cookies
    GET  /api/auth/me                     → current user
    POST /api/auth/password-reset-request → always returns 202
    POST /api/auth/password-reset-confirm → applies new password

Env vars (all required):
    JWT_SECRET               — long random string (no default)
    MONGO_URL                — mongodb://... connection string
    DB_NAME                  — database name (default: "app_db")
    FRONTEND_URL             — for CORS + email links
    APP_ENV                  — "production" forces Secure cookie flag
"""
import os
import re
import secrets
import time
from collections import defaultdict, deque
from datetime import datetime, timezone
from typing import Optional

import bcrypt
import jwt as pyjwt
from fastapi import APIRouter, Depends, HTTPException, Request, Response
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import BaseModel, EmailStr, Field

router = APIRouter()

# ── Config ────────────────────────────────────────────────────────
_JWT_SECRET       = os.environ["JWT_SECRET"]
_JWT_ALG          = "HS256"
_ACCESS_TTL_S     = 60 * 60          # 1 hour
_REFRESH_TTL_S    = 30 * 86400       # 30 days
_RESET_TTL_S      = 15 * 60          # 15 minutes
_APP_ENV          = os.environ.get("APP_ENV", "development")
_IS_PROD          = _APP_ENV == "production"

_mongo = AsyncIOMotorClient(
    os.environ["MONGO_URL"], maxPoolSize=10, minPoolSize=1,
)
db = _mongo[os.environ.get("DB_NAME", "app_db")]

# ── Sliding-window rate limiter (in-memory; per-IP) ───────────────
# For a personal-track single-instance app this is enough. Users who
# scale to N instances should swap this for a Redis-backed limiter.
_RL_WINDOWS: dict[str, deque] = defaultdict(deque)
_RL_LIMIT   = 5     # requests
_RL_WINDOW  = 900   # per 15 minutes


def _rate_limit_check(bucket: str, ip: str) -> None:
    """Raise 429 if this IP has exceeded the limit for `bucket`.

    Bucket separates limits per endpoint so a hostile /login spammer
    doesn't consume the /signup budget of a legitimate user on the
    same NAT'd IP."""
    now = time.time()
    key = f"{bucket}:{ip}"
    q = _RL_WINDOWS[key]
    while q and q[0] < now - _RL_WINDOW:
        q.popleft()
    if len(q) >= _RL_LIMIT:
        retry = int(_RL_WINDOW - (now - q[0]))
        raise HTTPException(
            429,
            detail={
                "reason":     "rate_limited",
                "retry_after_seconds": max(1, retry),
                "message":    "Too many requests. Please wait a moment.",
            },
        )
    q.append(now)


def _client_ip(request: Request) -> str:
    """Best-effort IP: honour X-Forwarded-For's leftmost hop (behind a
    trusted proxy). Falls back to socket peer."""
    xff = request.headers.get("x-forwarded-for", "")
    if xff:
        return xff.split(",")[0].strip()
    return request.client.host if request.client else "unknown"


# ── Password + token helpers ──────────────────────────────────────
def _hash_pw(pw: str) -> str:
    return bcrypt.hashpw(pw.encode(), bcrypt.gensalt(rounds=12)).decode()


def _verify_pw(pw: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(pw.encode(), hashed.encode())
    except Exception:
        return False


def _mint(token_type: str, user_id: str, email: str, ttl: int) -> str:
    now = int(time.time())
    payload = {
        "typ":     token_type,   # "access" | "refresh"
        "user_id": user_id,
        "email":   email,
        "iat":     now,
        "exp":     now + ttl,
    }
    return pyjwt.encode(payload, _JWT_SECRET, algorithm=_JWT_ALG)


def _cookie_kwargs(ttl: int) -> dict:
    return dict(
        httponly=True,
        secure=_IS_PROD,
        samesite="lax",
        max_age=ttl,
        path="/",
    )


def _set_auth_cookies(response: Response, user_id: str, email: str) -> None:
    response.set_cookie(
        "access_token",
        _mint("access", user_id, email, _ACCESS_TTL_S),
        **_cookie_kwargs(_ACCESS_TTL_S),
    )
    response.set_cookie(
        "refresh_token",
        _mint("refresh", user_id, email, _REFRESH_TTL_S),
        **_cookie_kwargs(_REFRESH_TTL_S),
    )


def _clear_auth_cookies(response: Response) -> None:
    response.delete_cookie("access_token",  path="/")
    response.delete_cookie("refresh_token", path="/")


# ── Auth dependency ───────────────────────────────────────────────
async def get_current_user(request: Request) -> dict:
    """Read + verify the access-token cookie. Never falls back to the
    Authorization header — the migration to httpOnly cookies is
    complete + intentional (localStorage tokens are XSS-vulnerable)."""
    token = request.cookies.get("access_token")
    if not token:
        raise HTTPException(401, "Not signed in")
    try:
        payload = pyjwt.decode(token, _JWT_SECRET, algorithms=[_JWT_ALG])
    except pyjwt.ExpiredSignatureError:
        raise HTTPException(401, "Session expired — please refresh")
    except Exception:
        raise HTTPException(401, "Invalid session")
    if payload.get("typ") != "access":
        raise HTTPException(401, "Wrong token type")
    return {"user_id": payload["user_id"], "email": payload["email"]}


# ── Pydantic models ───────────────────────────────────────────────
class SignupIn(BaseModel):
    email:    EmailStr
    password: str = Field(..., min_length=8, max_length=128)


class LoginIn(BaseModel):
    email:    EmailStr
    password: str


class ResetRequestIn(BaseModel):
    email: EmailStr


class ResetConfirmIn(BaseModel):
    token:        str = Field(..., min_length=32, max_length=128)
    new_password: str = Field(..., min_length=8,  max_length=128)


# ── Endpoints ─────────────────────────────────────────────────────
@router.post("/signup")
async def signup(body: SignupIn, request: Request, response: Response):
    _rate_limit_check("signup", _client_ip(request))
    existing = await db.users.find_one({"email": body.email.lower()})
    if existing:
        # Enumeration-safe: same-shape 4xx for taken-email and other
        # 4xx signup errors.
        raise HTTPException(409, "That email can't be used to sign up.")
    from uuid import uuid4
    user_id = uuid4().hex
    await db.users.insert_one({
        "user_id":    user_id,
        "email":      body.email.lower(),
        "password":   _hash_pw(body.password),
        "created_at": datetime.now(timezone.utc),
    })
    _set_auth_cookies(response, user_id, body.email.lower())
    return {"ok": True, "user_id": user_id, "email": body.email.lower()}


@router.post("/login")
async def login(body: LoginIn, request: Request, response: Response):
    _rate_limit_check("login", _client_ip(request))
    user = await db.users.find_one({"email": body.email.lower()})
    # ALWAYS run bcrypt (even if user is missing) to keep response
    # timing constant — prevents user-enumeration via timing side-channel.
    hashed = user.get("password") if user else _hash_pw("dummy-timing-guard")
    valid = _verify_pw(body.password, hashed) if user else False
    if not (user and valid):
        raise HTTPException(401, "Wrong email or password.")
    _set_auth_cookies(response, user["user_id"], user["email"])
    return {"ok": True, "user_id": user["user_id"], "email": user["email"]}


@router.post("/refresh")
async def refresh(request: Request, response: Response):
    """Rotate BOTH cookies from the refresh_token. Access-token TTL
    is 1h so callers should hit this endpoint on 401 and retry."""
    rt = request.cookies.get("refresh_token")
    if not rt:
        raise HTTPException(401, "No refresh token")
    try:
        payload = pyjwt.decode(rt, _JWT_SECRET, algorithms=[_JWT_ALG])
    except pyjwt.ExpiredSignatureError:
        _clear_auth_cookies(response)
        raise HTTPException(401, "Refresh token expired — please sign in again.")
    except Exception:
        raise HTTPException(401, "Invalid refresh token")
    if payload.get("typ") != "refresh":
        raise HTTPException(401, "Wrong token type")
    _set_auth_cookies(response, payload["user_id"], payload["email"])
    return {"ok": True}


@router.post("/logout")
async def logout(response: Response):
    _clear_auth_cookies(response)
    return {"ok": True}


@router.get("/me")
async def me(user=Depends(get_current_user)):
    return user


# ── Password-reset flow (enumeration-safe) ────────────────────────
@router.post("/password-reset-request", status_code=202)
async def password_reset_request(body: ResetRequestIn, request: Request):
    """Always returns 202 with a generic message — no matter whether
    the email exists. This is the OWASP-recommended pattern to prevent
    email enumeration via the reset endpoint."""
    _rate_limit_check("reset_request", _client_ip(request))
    email = body.email.lower()
    user = await db.users.find_one({"email": email})
    if user:
        token = secrets.token_urlsafe(48)   # ≥ 64 chars, cryptographically random
        await db.password_reset_tokens.insert_one({
            "token":      token,
            "user_id":    user["user_id"],
            "email":      email,
            "expires_at": time.time() + _RESET_TTL_S,
            "used":       False,
            "created_at": time.time(),
        })
        # In production, wire this to your email provider. Personal
        # Track apps default to console output so it's testable and
        # doesn't need SMTP config to start.
        frontend = os.environ.get("FRONTEND_URL", "http://localhost:3000")
        reset_link = f"{frontend}/reset-password?token={token}"
        print(f"[password-reset] {email} → {reset_link}",  # noqa: T201
              flush=True)
    return {
        "ok": True,
        "message": "If an account matches that email, we've sent a reset link.",
    }


@router.post("/password-reset-confirm")
async def password_reset_confirm(body: ResetConfirmIn, request: Request):
    """Consume a reset token (from the request BODY — never from a
    URL query param, per OWASP). Marks the token used, updates the
    password, and cleans up expired tokens opportunistically."""
    _rate_limit_check("reset_confirm", _client_ip(request))
    now = time.time()
    # Cleanup expired tokens (best-effort — cost is O(few))
    await db.password_reset_tokens.delete_many({"expires_at": {"$lt": now}})

    row = await db.password_reset_tokens.find_one({
        "token": body.token, "used": False,
    })
    if not row or row["expires_at"] < now:
        raise HTTPException(400, "That reset link is invalid or has expired.")
    # Mark used (single-use).
    await db.password_reset_tokens.update_one(
        {"_id": row["_id"]}, {"$set": {"used": True, "used_at": now}},
    )
    await db.users.update_one(
        {"user_id": row["user_id"]},
        {"$set": {"password": _hash_pw(body.new_password),
                  "password_changed_at": now}},
    )
    return {"ok": True, "message": "Password updated. You can sign in now."}
