"""
auth.py — Email/password JWT authentication.

Generated by AUREM CTO's Personal Track scaffolder.

Endpoints:
  POST /api/auth/signup   — {email, password} → {token}
  POST /api/auth/login    — {email, password} → {token}
  GET  /api/auth/me       — current user  (Bearer token)

Password hashing: bcrypt (12 rounds).  Tokens: JWT HS256, 7-day expiry.
"""
import os
import time
from datetime import datetime, timezone, timedelta
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Header
from pydantic import BaseModel, EmailStr, Field
import bcrypt
import jwt as pyjwt
from motor.motor_asyncio import AsyncIOMotorClient

router = APIRouter()

_JWT_SECRET = os.environ["JWT_SECRET"]         # required — no default
_JWT_ALG    = "HS256"
_TOKEN_TTL_DAYS = 7

_mongo = AsyncIOMotorClient(
    os.environ["MONGO_URL"],
    maxPoolSize=10, minPoolSize=1,
)
db = _mongo[os.environ.get("DB_NAME", "app_db")]


class SignupIn(BaseModel):
    email:    EmailStr
    password: str = Field(..., min_length=8, max_length=128)


class LoginIn(BaseModel):
    email:    EmailStr
    password: str


def _hash_pw(pw: str) -> str:
    return bcrypt.hashpw(pw.encode(), bcrypt.gensalt(rounds=12)).decode()


def _verify_pw(pw: str, hashed: str) -> bool:
    try:
        return bcrypt.checkpw(pw.encode(), hashed.encode())
    except Exception:
        return False


def _mint_token(user_id: str, email: str) -> str:
    payload = {
        "user_id": user_id,
        "email":   email,
        "iat":     int(time.time()),
        "exp":     int(time.time()) + _TOKEN_TTL_DAYS * 86400,
    }
    return pyjwt.encode(payload, _JWT_SECRET, algorithm=_JWT_ALG)


async def get_current_user(authorization: Optional[str] = Header(None)) -> dict:
    """FastAPI dependency — decodes the JWT and returns user info.
    Raises 401 on missing/bad token."""
    if not authorization or not authorization.startswith("Bearer "):
        raise HTTPException(401, "Missing bearer token")
    token = authorization.split(" ", 1)[1]
    try:
        payload = pyjwt.decode(token, _JWT_SECRET, algorithms=[_JWT_ALG])
    except pyjwt.ExpiredSignatureError:
        raise HTTPException(401, "Token expired")
    except Exception:
        raise HTTPException(401, "Invalid token")
    return {"user_id": payload["user_id"], "email": payload["email"]}


@router.post("/signup")
async def signup(body: SignupIn):
    existing = await db.users.find_one({"email": body.email.lower()})
    if existing:
        raise HTTPException(409, "Email already registered")
    from uuid import uuid4
    user_id = uuid4().hex
    await db.users.insert_one({
        "user_id":     user_id,
        "email":       body.email.lower(),
        "password":    _hash_pw(body.password),
        "created_at":  datetime.now(timezone.utc),
    })
    return {"token": _mint_token(user_id, body.email.lower()), "user_id": user_id}


@router.post("/login")
async def login(body: LoginIn):
    user = await db.users.find_one({"email": body.email.lower()})
    if not user or not _verify_pw(body.password, user["password"]):
        raise HTTPException(401, "Invalid email or password")
    return {"token": _mint_token(user["user_id"], user["email"]), "user_id": user["user_id"]}


@router.get("/me")
async def me(user=Depends(get_current_user)):
    return user
