"""
main.py — FastAPI backend entry point.

Generated by AUREM CTO. Ships with:
  • /api/health         — liveness probe
  • /api/items (CRUD)   — sample resource showing MongoDB read/write
  • /api/auth/*         — email+password JWT stub (see auth.py)

Run:
    cd api && uvicorn main:app --host 0.0.0.0 --port 8001 --reload
"""
import os
from datetime import datetime, timezone
from typing import Optional

from fastapi import FastAPI, HTTPException, Depends
from fastapi.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
from pydantic import BaseModel, Field
from bson import ObjectId

from auth import router as auth_router, get_current_user

# ── App + Mongo ────────────────────────────────────────────────
app = FastAPI(title="Personal Track API", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=[os.environ.get("FRONTEND_URL", "http://localhost:3000")],
    allow_credentials=True,
    allow_methods=["*"], allow_headers=["*"],
)
app.include_router(auth_router, prefix="/api/auth", tags=["auth"])

_mongo = AsyncIOMotorClient(
    os.environ["MONGO_URL"],
    maxPoolSize=10, minPoolSize=1, maxIdleTimeMS=30_000,
)
db = _mongo[os.environ.get("DB_NAME", "app_db")]


# ── Models ────────────────────────────────────────────────────
class ItemIn(BaseModel):
    title: str = Field(..., min_length=1, max_length=200)
    body: Optional[str] = None


class Item(ItemIn):
    id: str
    user_id: str
    created_at: datetime


# ── Routes ────────────────────────────────────────────────────
@app.get("/api/health")
async def health():
    return {"ok": True, "service": "personal-track-api"}


@app.get("/api/items")
async def list_items(user=Depends(get_current_user)):
    cur = db.items.find({"user_id": user["user_id"]}).sort("created_at", -1)
    out = []
    async for row in cur:
        out.append({
            "id":         str(row["_id"]),
            "title":      row["title"],
            "body":       row.get("body"),
            "user_id":    row["user_id"],
            "created_at": row["created_at"],
        })
    return {"items": out}


@app.post("/api/items")
async def create_item(payload: ItemIn, user=Depends(get_current_user)):
    doc = {
        **payload.model_dump(),
        "user_id":    user["user_id"],
        "created_at": datetime.now(timezone.utc),
    }
    res = await db.items.insert_one(doc)
    return {"id": str(res.inserted_id), **payload.model_dump()}


@app.delete("/api/items/{item_id}")
async def delete_item(item_id: str, user=Depends(get_current_user)):
    try:
        oid = ObjectId(item_id)
    except Exception:
        raise HTTPException(400, "Invalid item id")
    res = await db.items.delete_one({"_id": oid, "user_id": user["user_id"]})
    if res.deleted_count == 0:
        raise HTTPException(404, "Item not found")
    return {"ok": True}
