"""
projects.py — AUREM Dev
E2E project creation router:
  POST /api/aurem-dev/projects/create
      → generate code (AI)
      → push to GitHub
      → provision MongoDB
      → return {project_id, repo_url, db_conn, files}
"""
from __future__ import annotations
import asyncio
import json as _json
import logging
import time as _t
import uuid
from typing import Optional

from fastapi import APIRouter, HTTPException, Header
from pydantic import BaseModel

from cto_services.auth import current_dev
from cto_services.db import get_db
from services.project_generator import generate_project, get_project_files
from services.github_auto import create_and_push
from services.mongo_provisioner import provision_project_db
from services.doc_generator import generate_all_docs

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/projects", tags=["AUREM Dev Projects"])


class CreateProjectBody(BaseModel):
    idea: str
    stack_id: str = "react-fastapi"
    repo_name: Optional[str] = None
    private_repo: bool = True
    provision_db: bool = True


@router.post("/create")
async def create_project(
    body: CreateProjectBody,
    authorization: str = Header(None),
) -> dict:
    """
    Full E2E: idea → generated code → GitHub repo → MongoDB DB.
    Returns everything the user needs to start building.
    """
    me = await current_dev(authorization)
    user_id = me["user_id"]

    # 1. Generate code
    # Iter 147 — hard cap at 80s. The full E2E (LLM + GitHub push + DB
    # provision) used to run synchronously inside one HTTP call. On
    # Cloudflare-fronted prod this hit the 100s edge limit roughly half
    # the time and returned 524 with no log line; user saw "invalid or
    # incomplete response". Now we time-box the LLM step, return a
    # friendly 504, and let the user retry instead of an opaque
    # Cloudflare error.
    logger.info(f"[projects] generating for user={user_id} idea={body.idea[:60]}")
    try:
        gen = await asyncio.wait_for(
            generate_project(body.idea, body.stack_id),
            timeout=80.0,
        )
    except asyncio.TimeoutError:
        raise HTTPException(504, {
            "code": "code_generation_timeout",
            "msg":  "Code generation took longer than 80s. The LLM is likely "
                    "rate-limited or the upstream model is slow. Please try "
                    "again in a few seconds.",
        })
    if not gen.get("ok"):
        raise HTTPException(502, f"Code generation failed: {gen.get('error')}")

    project_id = gen["project_id"]
    files = await get_project_files(project_id)

    result: dict = {
        "ok": True,
        "project_id": project_id,
        "stack": gen["stack"],
        "description": gen["description"],
        "plan": gen["plan"],
        "files_count": len(files),
    }

    # 2. Push to GitHub (prefer per-user OAuth token if connected)
    repo_name = body.repo_name or f"aurem-{project_id}"
    user_gh_token = None
    db = get_db()
    if db is not None:
        u = await db.dev_users.find_one(
            {"user_id": user_id}, {"_id": 0, "github": 1}
        )
        user_gh_token = ((u or {}).get("github") or {}).get("access_token")
    try:
        gh = await create_and_push(
            project_name=repo_name,
            files=files,
            description=gen.get("description", "Generated by AUREM Dev"),
            private=body.private_repo,
            user_token=user_gh_token,
        )
        result["github"] = {
            "ok": gh["ok"],
            "repo_url": gh.get("repo_url"),
            "clone_url": gh.get("clone_url"),
            "pushed_files": len(gh.get("pushed", [])),
        }
        logger.info(f"[projects] pushed to GitHub: {gh.get('repo_url')}")
    except Exception as e:
        logger.warning(f"[projects] GitHub push failed (non-fatal): {e}")
        result["github"] = {"ok": False, "error": str(e)}

    # 3. Provision MongoDB
    if body.provision_db:
        try:
            db = await provision_project_db(project_id)
            result["database"] = {
                "ok": db["ok"],
                "db_name": db.get("db_name"),
                "connection_string": db.get("connection_string"),
                "source": db.get("source"),
            }
            logger.info(f"[projects] DB provisioned: {db.get('db_name')}")
        except Exception as e:
            logger.warning(f"[projects] DB provision failed (non-fatal): {e}")
            result["database"] = {"ok": False, "error": str(e)}

    return result


@router.get("/{project_id}/files")
async def get_files(
    project_id: str,
    authorization: str = Header(None),
) -> dict:
    """Get all generated files for a project."""
    await current_dev(authorization)


# ── Two-phase build: plan → review → build ─────────────────────────────

@router.post("/plan")
async def plan_project(
    body: CreateProjectBody,
    authorization: str = Header(None),
) -> dict:
    """Phase 1: Generate the 6-doc plan. User reviews before building."""
    await current_dev(authorization)
    docs = await generate_all_docs(body.idea)
    db = get_db()
    plan_id = uuid.uuid4().hex[:10]
    if db is not None:
        await db.project_plans.insert_one({
            "plan_id": plan_id,
            "idea": body.idea,
            "stack_id": body.stack_id,
            "docs": docs,
            "status": "pending_review",
            "created_at": _t.time(),
        })
    return {
        "ok": True,
        "plan_id": plan_id,
        "docs": docs,
        "next": f"POST /api/aurem-dev/projects/build/{plan_id}",
    }


@router.post("/build/{plan_id}")
async def build_from_plan(
    plan_id: str,
    authorization: str = Header(None),
) -> dict:
    """Phase 2: Build project from a reviewed plan."""
    await current_dev(authorization)
    db = get_db()
    plan = None
    if db is not None:
        plan = await db.project_plans.find_one({"plan_id": plan_id}, {"_id": 0})
    if not plan:
        raise HTTPException(404, "Plan not found")

    docs_context = "\n\n".join([
        f"## {v['name']}\n{_json.dumps(v['data'], indent=2)}"
        for v in (plan.get("docs") or {}).values() if v.get("ok")
    ])
    enriched = f"{plan['idea']}\n\nFollow these specs exactly:\n{docs_context[:3000]}"

    gen = await generate_project(enriched, plan.get("stack_id", "react-fastapi"))
    if db is not None:
        await db.project_plans.update_one(
            {"plan_id": plan_id},
            {"$set": {
                "status": "built",
                "project_id": gen.get("project_id"),
                "built_at": _t.time(),
            }},
        )
    return {**gen, "plan_id": plan_id}

    files = await get_project_files(project_id)
    if not files:
        raise HTTPException(404, "Project not found")
    return {"ok": True, "project_id": project_id, "files": files}
