/**
 * lib/aurem-db.js — SDK generated by AUREM CTO's Personal Track scaffolder.
 *
 * Talks to AUREM's managed shared MongoDB via a scoped REST API
 * instead of a raw connection string. Same design goal as the
 * Python client — the generated app NEVER carries raw DB credentials.
 *
 * Config (.env.local):
 *   AUREM_API_BASE   = https://api.auremcto.com
 *   AUREM_APP_ID     = pt_xxxxxxxx (auto-injected at materialize time)
 *   AUREM_APP_TOKEN  = eyJ... (JWT scoped to your app)
 *
 * Usage:
 *   import { db } from "@/lib/aurem-db";
 *   const list = await db.collection("todos").find({});
 *   const created = await db.collection("todos").insert({ title: "Ship it" });
 */
class _Collection {
  constructor(client, name) { this.c = client; this.name = name; }
  async find(filter = {}, limit = 50, sort = null) {
    const r = await this.c._post(`${this.name}/find`, { filter, limit, sort });
    return (r && r.docs) || [];
  }
  async findOne(filter) {
    const r = await this.c._post(`${this.name}/find-one`, { filter });
    return r && r.doc;
  }
  async insert(data, schema = null) {
    return this.c._post(`${this.name}/insert`, { data, schema });
  }
  async update(filter, patch) {
    return this.c._request("PATCH", `${this.name}/update`, { filter, patch });
  }
  async delete(filter) {
    return this.c._request("DELETE", `${this.name}/delete`, { filter });
  }
}

class AuremDB {
  constructor() {
    this.base   = process.env.AUREM_API_BASE || "https://api.auremcto.com";
    this.appId  = process.env.AUREM_APP_ID;
    this.token  = process.env.AUREM_APP_TOKEN;
    if (!this.appId || !this.token) {
      throw new Error(
        "AUREM_APP_ID and AUREM_APP_TOKEN must be set. Materialize your " +
        "draft to get them auto-injected."
      );
    }
  }
  collection(name) { return new _Collection(this, name); }
  async _request(method, path, body = null) {
    const url = `${this.base}/api/managed-db/${this.appId}/${path}`;
    const r = await fetch(url, {
      method,
      headers: {
        "Authorization": `Bearer ${this.token}`,
        "Content-Type":  "application/json",
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!r.ok) {
      const text = await r.text().catch(() => "");
      throw new Error(`AUREM DB ${method} ${path} failed: ${r.status} ${text}`);
    }
    return r.json();
  }
  async _post(path, body) { return this._request("POST", path, body); }
}

export const db = new AuremDB();
export default db;
