"""Iter 328 · tests for scripts/inventory_append.py

Test-first: idempotent append semantics, formatting per kind, section
auto-creation, missing-file handling.

Run: cd /app/backend && python -m pytest tests/test_inventory_append.py -v
"""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest


_SPEC = importlib.util.spec_from_file_location(
    "inventory_append",
    Path("/app/backend/scripts/inventory_append.py"),
)
inventory_append = importlib.util.module_from_spec(_SPEC)  # type: ignore
sys.modules["inventory_append"] = inventory_append
_SPEC.loader.exec_module(inventory_append)  # type: ignore


@pytest.fixture
def temp_inv(monkeypatch, tmp_path):
    """Point INV at a temp file seeded with a minimal inventory doc."""
    inv = tmp_path / "SYSTEM_INVENTORY.md"
    inv.write_text(
        "# Test Inventory\n\n## Existing section\n\n"
        "| File | Prefix | Routes | Purpose |\n"
        "|---|---|---|---|\n"
        "| `routers/auth.py` | `/auth` | 10 | login |\n"
    )
    monkeypatch.setattr(inventory_append, "INV", inv)
    return inv


def test_router_append_first_time(temp_inv):
    result = inventory_append.append(
        [{"kind": "router", "path": "routers/dev_sse_probe.py",
          "prefix": "/aurem-dev/_iter309_probe", "routes": 3,
          "purpose": "test-only synthetic SSE probe"}],
        iter_num=309,
    )
    assert result.get("error") is None
    assert len(result["appended"]) == 1
    assert result["skipped"] == []
    text = temp_inv.read_text()
    assert "routers/dev_sse_probe.py" in text
    assert "Iter 309" in text
    assert "🔁 Ripple appends" in text


def test_router_append_idempotent(temp_inv):
    change = {"kind": "router", "path": "routers/dev_sse_probe.py",
              "prefix": "/x", "routes": 1, "purpose": "test"}
    r1 = inventory_append.append([change], iter_num=309)
    r2 = inventory_append.append([change], iter_num=309)
    assert len(r1["appended"]) == 1
    assert r2["appended"] == []
    assert len(r2["skipped"]) == 1


def test_envvar_append_and_dedupe(temp_inv):
    change = {"kind": "envvar", "name": "AUREM_ENABLE_SSE_PROBE",
              "purpose": "gate dev SSE probe", "default": "0"}
    r1 = inventory_append.append([change], iter_num=309)
    r2 = inventory_append.append([change], iter_num=309)
    assert len(r1["appended"]) == 1
    assert r2["appended"] == []
    text = temp_inv.read_text()
    assert "AUREM_ENABLE_SSE_PROBE" in text
    # HTML-comment idempotence marker should appear exactly once.
    assert text.count("<!-- inv:envvar:AUREM_ENABLE_SSE_PROBE -->") == 1


def test_loop_run_log_kind(temp_inv):
    change = {"kind": "loop_run_log_kind", "value": "sse_probe_client",
              "purpose": "Iter 309 reconnect telemetry"}
    r = inventory_append.append([change], iter_num=309)
    assert r["appended"]
    text = temp_inv.read_text()
    assert "loop_run_log kind='sse_probe_client'" in text


def test_multiple_kinds_one_call(temp_inv):
    changes = [
        {"kind": "router", "path": "routers/x.py", "prefix": "/x",
         "routes": 1, "purpose": "a"},
        {"kind": "envvar", "name": "X_ENV", "purpose": "b", "default": "0"},
        {"kind": "collection", "name": "x_coll", "purpose": "c"},
    ]
    r = inventory_append.append(changes, iter_num=328)
    assert len(r["appended"]) == 3


def test_partial_dedupe(temp_inv):
    """One new, one already-present → append 1, skip 1."""
    a = {"kind": "envvar", "name": "A_ENV", "purpose": "a", "default": "0"}
    b = {"kind": "envvar", "name": "B_ENV", "purpose": "b", "default": "0"}
    inventory_append.append([a], iter_num=100)
    r = inventory_append.append([a, b], iter_num=101)
    assert len(r["appended"]) == 1
    assert len(r["skipped"]) == 1


def test_missing_inventory_file(monkeypatch, tmp_path):
    monkeypatch.setattr(
        inventory_append, "INV", tmp_path / "nonexistent.md",
    )
    r = inventory_append.append(
        [{"kind": "router", "path": "x", "prefix": "/x",
          "routes": 1, "purpose": "y"}],
        iter_num=1,
    )
    assert r.get("error")


def test_ripple_section_appears_only_once(temp_inv):
    """Multiple append calls must not create duplicate Ripple section headers."""
    inventory_append.append(
        [{"kind": "envvar", "name": "A", "purpose": "a", "default": "0"}],
        iter_num=1)
    inventory_append.append(
        [{"kind": "envvar", "name": "B", "purpose": "b", "default": "0"}],
        iter_num=2)
    text = temp_inv.read_text()
    assert text.count(
        "🔁 Ripple appends (auto-generated by scripts/inventory_append.py)"
    ) == 1
