"""
Iter 212m-30 (PR-2) — Repo Indexing + Founder Offer.

Three suites:

  1. Repo indexing static analysis (`services/repo_indexing.py`)
     – Pure-function tests for `_analyse_tree` + `_render_codebase_md`
       with hand-rolled GitHub tree fixtures. NO network.
     – `build_repo_index()` end-to-end with `_fetch_tree`, `_fetch_file`,
       and `commit_files` patched so the call hits Mongo only.

  2. Founder offer router (`routers/founder_offer.py`)
     – Atomic decrement under concurrent claims.
     – Per-user 3-claim cap.
     – Cancel restores the spot.
     – Confirm flips fix_status and triggers the runner.

  3. Auth signup (`routers/auth.py`)
     – `created_at` is persisted and surfaced via /auth/me + signup body.

Every test that needs a Mongo handle uses MongoMock-like wrappers built
inline so we don't depend on a live cluster.
"""
from __future__ import annotations

import asyncio
import time
from datetime import datetime, timezone
from unittest.mock import patch, AsyncMock, MagicMock

import pytest


# ════════════════════════════════════════════════════════════════════
# 1. Repo indexing — pure functions
# ════════════════════════════════════════════════════════════════════

def _tree(*entries):
    """Tiny helper: build the GitHub-shaped tree list.
    Each entry is a (path, type) tuple."""
    return [{"path": p, "type": t} for p, t in entries]


def test_analyse_tree_dominant_language_picks_most_common():
    from services.repo_indexing import _analyse_tree
    m = _analyse_tree(_tree(
        ("main.py", "blob"),
        ("util.py", "blob"),
        ("api/route.py", "blob"),
        ("frontend/src/App.tsx", "blob"),
    ))
    assert m["dominant_language"] == "Python"
    assert m["language_breakdown"]["py"] == 3
    assert m["language_breakdown"]["tsx"] == 1


def test_analyse_tree_detects_known_entry_points():
    from services.repo_indexing import _analyse_tree
    m = _analyse_tree(_tree(
        ("main.py", "blob"),
        ("frontend/src/App.tsx", "blob"),
        ("README.md", "blob"),
    ))
    assert "main.py" in m["entry_points"]
    assert "frontend/src/App.tsx" in m["entry_points"]


def test_analyse_tree_finds_service_folders_and_tests():
    from services.repo_indexing import _analyse_tree
    m = _analyse_tree(_tree(
        ("backend",            "tree"),
        ("backend/services",   "tree"),
        ("backend/services/x.py", "blob"),
        ("backend/routers",    "tree"),
        ("backend/routers/y.py", "blob"),
        ("tests",              "tree"),
        ("tests/test_x.py",    "blob"),
    ))
    assert "backend/services" in m["service_folders"]
    assert "backend/routers" in m["service_folders"]
    assert m["has_tests"] is True


def test_analyse_tree_picks_root_dep_files_and_nested_ones():
    from services.repo_indexing import _analyse_tree
    m = _analyse_tree(_tree(
        ("package.json",            "blob"),
        ("backend/requirements.txt","blob"),
        ("frontend/yarn.lock",      "blob"),
    ))
    assert "package.json" in m["dependency_files"]
    assert any(d.endswith("requirements.txt") for d in m["dependency_files"])
    assert any(d.endswith("yarn.lock") for d in m["dependency_files"])


def test_analyse_tree_no_files_returns_unknown_lang():
    from services.repo_indexing import _analyse_tree
    m = _analyse_tree([])
    assert m["dominant_language"] == "unknown"
    assert m["file_count"] == 0
    assert m["has_tests"] is False


def test_render_codebase_md_idempotent_layout():
    """Two runs over the same metrics differ only in the timestamp
    line — important so the GitHub diff stays clean across runs."""
    from services.repo_indexing import _render_codebase_md
    metrics = {
        "dominant_language": "Python",
        "language_breakdown": {"py": 5, "tsx": 2},
        "entry_points": ["main.py"],
        "service_folders": ["backend/services"],
        "dependency_files": ["requirements.txt"],
        "has_tests": True,
        "file_count": 7,
    }
    a = _render_codebase_md(
        owner="o", repo="r", branch="main",
        metrics=metrics, readme_title="Title",
        readme_summary="Summary",
    )
    b = _render_codebase_md(
        owner="o", repo="r", branch="main",
        metrics=metrics, readme_title="Title",
        readme_summary="Summary",
    )
    # Strip the dated header before comparing
    def _strip_date(s):
        return [ln for ln in s.splitlines() if "Auto-generated by Aurem CTO" not in ln]
    assert _strip_date(a) == _strip_date(b)
    assert "## Languages (by file count)" in a
    assert "## Entry points" in a
    assert "## Service / layer folders" in a
    assert "## Dependency manifests" in a


# ════════════════════════════════════════════════════════════════════
# 2. Repo indexing — build_repo_index end-to-end (Mongo-only)
# ════════════════════════════════════════════════════════════════════

@pytest.mark.asyncio
async def test_build_repo_index_bails_when_project_missing():
    from services import repo_indexing

    fake_db = MagicMock()
    fake_db.cto_projects = MagicMock()
    fake_db.cto_projects.find_one = AsyncMock(return_value=None)

    with patch("services.repo_indexing.get_db", return_value=fake_db):
        out = await repo_indexing.build_repo_index(
            user_id="u", project_id="pX", commit=False,
        )
    assert out["ok"] is False
    assert any("not found" in e for e in out["errors"])


@pytest.mark.asyncio
async def test_build_repo_index_happy_path_no_commit():
    """Happy path with a mocked tree + mocked README + commit=False.
    Asserts the persisted record's shape."""
    from services import repo_indexing

    tree = _tree(
        ("main.py", "blob"),
        ("requirements.txt", "blob"),
        ("backend/services/x.py", "blob"),
        ("tests/test_x.py", "blob"),
    )
    proj = {
        "project_id": "p1", "user_id": "u",
        "github_owner": "acme", "github_repo": "site",
        "branch": "main",
        "github_token": "ghp_fake",
    }

    fake_db = MagicMock()
    fake_db.cto_projects = MagicMock()
    fake_db.cto_projects.find_one = AsyncMock(return_value=proj)
    fake_db.repo_index = MagicMock()
    fake_db.repo_index.update_one = AsyncMock(return_value=None)
    fake_db.repo_index.create_index = AsyncMock(return_value=None)

    with patch("services.repo_indexing.get_db", return_value=fake_db), \
         patch("services.repo_indexing._fetch_tree",
               new=AsyncMock(return_value=(tree, False))), \
         patch("services.repo_indexing._fetch_file",
               new=AsyncMock(return_value="# Acme\n\nA tiny demo site for the test suite.")), \
         patch("services.repo_indexing.commit_files",
               new=AsyncMock()) as mock_commit:
        out = await repo_indexing.build_repo_index(
            user_id="u", project_id="p1", commit=False,
        )

    assert out["ok"] is True
    assert out["dominant_language"] == "Python"
    assert "main.py" in out["entry_points"]
    assert "backend/services" in out["service_folders"]
    assert out["has_tests"] is True
    assert out["readme_title"] == "Acme"
    assert "tiny demo site" in (out["readme_summary"] or "")
    # commit=False should NOT have called commit_files.
    assert mock_commit.await_count == 0
    # Persisted via upsert
    fake_db.repo_index.update_one.assert_awaited()


@pytest.mark.asyncio
async def test_build_repo_index_commits_when_commit_true():
    from services import repo_indexing

    tree = _tree(("main.py", "blob"))
    proj = {
        "project_id": "p1", "user_id": "u",
        "github_owner": "acme", "github_repo": "site",
        "branch": "main", "github_token": "ghp_fake",
    }
    fake_db = MagicMock()
    fake_db.cto_projects = MagicMock()
    fake_db.cto_projects.find_one = AsyncMock(return_value=proj)
    fake_db.repo_index = MagicMock()
    fake_db.repo_index.update_one = AsyncMock(return_value=None)
    fake_db.repo_index.create_index = AsyncMock(return_value=None)

    with patch("services.repo_indexing.get_db", return_value=fake_db), \
         patch("services.repo_indexing._fetch_tree",
               new=AsyncMock(return_value=(tree, False))), \
         patch("services.repo_indexing._fetch_file",
               new=AsyncMock(return_value=None)), \
         patch("services.repo_indexing.commit_files",
               new=AsyncMock(return_value={"ok": True, "sha": "abc1234",
                                            "html_url": "https://gh/c/abc1234"})) as mock_commit:
        out = await repo_indexing.build_repo_index(
            user_id="u", project_id="p1", commit=True,
        )

    mock_commit.assert_awaited_once()
    args, kwargs = mock_commit.await_args
    assert "CODEBASE.md" in kwargs["files"]
    assert out["commit_sha"] == "abc1234"


# ════════════════════════════════════════════════════════════════════
# 3. Founder offer — atomic spot decrement
# ════════════════════════════════════════════════════════════════════

class _SingletonFakeMongo:
    """A microscopic Mongo stand-in that supports the operations the
    founder_offer router actually uses (find_one, find_one_and_update
    with $inc + $expr, update_one, insert_one). Single-threaded so we
    can model the "atomic" guarantee with a regular dict."""

    def __init__(self):
        # founder_offer singleton
        self._offer = None
        self.claims: dict[str, dict] = {}        # claim_id → doc
        self.users: dict[str, dict] = {}

    # ── helpers ────────────────────────────────────────────────
    def reset(self):
        self._offer = None
        self.claims.clear()

    # ── founder_offer collection ───────────────────────────────
    class _Offer:
        def __init__(self, outer): self._o = outer
        async def find_one(self, q):
            return dict(self._o._offer) if self._o._offer else None
        async def find_one_and_update(self, q, update, upsert=False, return_document=False):
            o = self._o
            if o._offer is None:
                if "$setOnInsert" in update and upsert:
                    o._offer = dict(update["$setOnInsert"])
                else:
                    return None
            if "$expr" in q:
                if not (o._offer["spots_claimed"] < o._offer["total_spots"]
                        and o._offer.get("is_active", True)):
                    return None
            if "$inc" in update:
                for k, v in update["$inc"].items():
                    o._offer[k] = o._offer.get(k, 0) + v
            if "$set" in update:
                o._offer.update(update["$set"])
            return dict(o._offer)
        async def update_one(self, q, update):
            o = self._o
            if o._offer is None:
                return type("R", (), {"matched_count": 0})()
            if "spots_claimed" in q and isinstance(q["spots_claimed"], dict):
                if not (o._offer["spots_claimed"] > q["spots_claimed"].get("$gt", -1)):
                    return type("R", (), {"matched_count": 0})()
            if "$inc" in update:
                for k, v in update["$inc"].items():
                    o._offer[k] = o._offer.get(k, 0) + v
            return type("R", (), {"matched_count": 1})()

    # ── user_seo_claims collection ─────────────────────────────
    class _Claims:
        def __init__(self, outer): self._o = outer
        def find(self, q):
            outer = self._o
            matches = [
                v for v in outer.claims.values()
                if all(_match(v, k, val) for k, val in q.items())
            ]
            class _Cursor:
                def __init__(self, items): self.items = items
                def sort(self, *_args): return self
                async def to_list(self, length): return list(self.items)[:length]
            return _Cursor(matches)
        async def find_one(self, q):
            for v in self._o.claims.values():
                if all(_match(v, k, val) for k, val in q.items()):
                    return dict(v)
            return None
        async def find_one_and_update(self, q, update, return_document=False):
            target = None
            for v in self._o.claims.values():
                if all(_match(v, k, val) for k, val in q.items()):
                    target = v
                    break
            if target is None:
                return None
            if "$set" in update:
                target.update(update["$set"])
            return dict(target)
        async def insert_one(self, doc):
            self._o.claims[doc["claim_id"]] = dict(doc)
            return type("R", (), {"inserted_id": doc["claim_id"]})()
        async def update_one(self, q, update):
            target = None
            for v in self._o.claims.values():
                if all(_match(v, k, val) for k, val in q.items()):
                    target = v
                    break
            if target is None:
                return type("R", (), {"matched_count": 0})()
            if "$set" in update:
                target.update(update["$set"])
            return type("R", (), {"matched_count": 1})()
        async def create_index(self, *a, **k):
            return None

    # ── dev_users ──────────────────────────────────────────────
    class _Users:
        def __init__(self, outer): self._o = outer
        async def find_one(self, q, projection=None):
            uid = q.get("user_id")
            return self._o.users.get(uid)
        async def insert_one(self, doc):
            self._o.users[doc["user_id"]] = dict(doc)

    @property
    def founder_offer(self): return self._Offer(self)
    @property
    def user_seo_claims(self): return self._Claims(self)
    @property
    def dev_users(self): return self._Users(self)


def _match(doc, key, val):
    if isinstance(val, dict):
        if "$ne" in val:
            return doc.get(key) != val["$ne"]
        if "$gt" in val:
            return (doc.get(key) or 0) > val["$gt"]
    return doc.get(key) == val


@pytest.mark.asyncio
async def test_offer_status_returns_remaining():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    with patch("routers.founder_offer.get_db", return_value=db):
        r = await founder_offer.offer_status()
    assert r["total"] == 500
    assert r["remaining"] == 500
    assert r["is_active"] is True


@pytest.mark.asyncio
async def test_claim_decrements_atomic_and_returns_preview():
    from routers import founder_offer
    db = _SingletonFakeMongo()

    async def fake_seo_run(*, user_id, project_id, options):
        return {
            "ok": True, "patches": [
                {"path": "index.html", "action": "modify", "reason": "x"},
            ],
            "errors": [], "committed": False,
        }

    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.run_seo_fixes", new=AsyncMock(side_effect=fake_seo_run)):
        r = await founder_offer.claim_offer(
            founder_offer._ClaimBody(repo_id="p1", site_url=""),
            authorization="Bearer x",
        ) if False else None  # placeholder to satisfy lint
        # Bypass FastAPI Depends by calling the function via the
        # underlying coroutine — `current_dev` is the only auth dep.
        with patch("routers.founder_offer.current_dev",
                   new=AsyncMock(return_value={"user_id": "u1"})):
            r = await founder_offer.claim_offer(
                founder_offer._ClaimBody(repo_id="p1", site_url=""),
                authorization="Bearer x",
            )

    assert r["success"] is True
    assert "claim_id" in r
    assert r["preview"]["issues_found"] == 1
    assert r["preview"]["files_affected"] == ["index.html"]
    assert db._offer["spots_claimed"] == 1


@pytest.mark.asyncio
async def test_per_user_cap_enforced_at_three():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    # Pre-seed 3 claims for the user.
    now = datetime.now(timezone.utc)
    for i in range(3):
        db.claims[f"c{i}"] = {
            "claim_id": f"c{i}", "user_id": "u1",
            "repo_id": f"p{i}", "fix_status": "completed",
            "created_at": now,
        }

    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u1"})), \
         patch("routers.founder_offer.run_seo_fixes",
               new=AsyncMock()):
        r = await founder_offer.claim_offer(
            founder_offer._ClaimBody(repo_id="p_new", site_url=""),
            authorization="Bearer x",
        )
    assert r["success"] is False
    assert r["action"] == "upgrade"


@pytest.mark.asyncio
async def test_claim_sold_out_when_counter_hits_total():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    # Force the singleton to look already-full.
    db._offer = {
        "_id": "global", "total_spots": 500,
        "spots_claimed": 500, "is_active": True,
        "created_at": datetime.now(timezone.utc),
    }

    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u1"})), \
         patch("routers.founder_offer.run_seo_fixes", new=AsyncMock()):
        r = await founder_offer.claim_offer(
            founder_offer._ClaimBody(repo_id="p1", site_url=""),
            authorization="Bearer x",
        )

    assert r["success"] is False
    assert r["action"] == "sold_out"
    assert db._offer["spots_claimed"] == 500   # never crossed total


@pytest.mark.asyncio
async def test_cancel_restores_spot_only_when_preview():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    db._offer = {
        "_id": "global", "total_spots": 500,
        "spots_claimed": 5, "is_active": True,
        "created_at": datetime.now(timezone.utc),
    }
    db.claims["c1"] = {
        "claim_id": "c1", "user_id": "u1", "repo_id": "p1",
        "fix_status": "preview",
        "created_at": datetime.now(timezone.utc),
    }
    db.claims["c2"] = {
        "claim_id": "c2", "user_id": "u1", "repo_id": "p2",
        "fix_status": "completed",
        "created_at": datetime.now(timezone.utc),
    }

    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u1"})):
        ok = await founder_offer.cancel_offer(
            founder_offer._CancelBody(claim_id="c1"),
            authorization="Bearer x",
        )
        noop = await founder_offer.cancel_offer(
            founder_offer._CancelBody(claim_id="c2"),
            authorization="Bearer x",
        )

    assert ok["success"] is True
    assert noop["success"] is False
    assert db._offer["spots_claimed"] == 4   # restored once, not twice
    assert db.claims["c1"]["fix_status"] == "cancelled"
    assert db.claims["c2"]["fix_status"] == "completed"   # untouched


@pytest.mark.asyncio
async def test_confirm_flips_status_and_kicks_runner():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    db.claims["c1"] = {
        "claim_id": "c1", "user_id": "u1", "repo_id": "p1",
        "fix_status": "preview", "site_url": "",
        "created_at": datetime.now(timezone.utc),
    }

    started = asyncio.Event()

    async def fake_real_fix(**kwargs):
        started.set()

    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u1"})), \
         patch("routers.founder_offer._run_real_fix",
               side_effect=fake_real_fix) as runner:
        r = await founder_offer.confirm_offer(
            founder_offer._ConfirmBody(claim_id="c1"),
            authorization="Bearer x",
        )
        # Give the create_task a chance to run.
        await asyncio.wait_for(started.wait(), timeout=2.0)

    assert r["success"] is True
    assert r["fix_status"] == "running"
    assert db.claims["c1"]["fix_status"] == "running"
    runner.assert_called_once()


@pytest.mark.asyncio
async def test_user_status_reports_zero_for_new_user():
    from routers import founder_offer
    db = _SingletonFakeMongo()
    db.users["u1"] = {
        "user_id": "u1",
        "created_at": datetime.now(timezone.utc),
    }
    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u1"})):
        r = await founder_offer.offer_user_status(authorization="Bearer x")
    assert r["repos_claimed"] == 0
    assert r["has_fully_claimed"] is False
    assert isinstance(r["days_since_signup"], float)
    assert r["days_since_signup"] < 0.1   # signup just now


@pytest.mark.asyncio
async def test_user_status_handles_legacy_epoch_seconds_created_at():
    """Some rows from older iterations stored `created_at` as a unix
    epoch float instead of a tz-aware datetime. The router must
    surface a sensible days_since_signup for them, not None."""
    from routers import founder_offer
    db = _SingletonFakeMongo()
    db.users["u_legacy"] = {
        "user_id": "u_legacy",
        # ~5 days ago, in epoch seconds
        "created_at": time.time() - (5 * 86400),
    }
    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u_legacy"})):
        r = await founder_offer.offer_user_status(authorization="Bearer x")
    assert isinstance(r["days_since_signup"], float)
    assert 4.9 < r["days_since_signup"] < 5.1


@pytest.mark.asyncio
async def test_user_status_returns_null_for_missing_created_at():
    """No created_at at all → days_since_signup is None and the
    frontend treats the user as 'expired' (won't show the tint)."""
    from routers import founder_offer
    db = _SingletonFakeMongo()
    db.users["u_old"] = {"user_id": "u_old"}
    with patch("routers.founder_offer.get_db", return_value=db), \
         patch("routers.founder_offer.current_dev",
               new=AsyncMock(return_value={"user_id": "u_old"})):
        r = await founder_offer.offer_user_status(authorization="Bearer x")
    assert r["days_since_signup"] is None


# ════════════════════════════════════════════════════════════════════
# 4. Source pins — wiring + behaviour
# ════════════════════════════════════════════════════════════════════

def test_main_wires_both_routers():
    """Guard against silent un-wiring of the PR-2 routers."""
    src = open("/app/backend/main.py").read()
    assert "from routers.repo_indexing import router as repo_indexing_router" in src
    assert "from routers.founder_offer import router as founder_offer_router" in src
    assert "app.include_router(repo_indexing_router" in src
    assert "app.include_router(founder_offer_router" in src


def test_repo_indexing_router_uses_correct_path():
    """The user spec required POST /api/aurem-dev/repos/{repo_id:path}/index."""
    src = open("/app/backend/routers/repo_indexing.py").read()
    assert "/repos" in src
    assert "{repo_id:path}/index" in src
    assert ".post(" in src


def test_signup_persists_created_at():
    src = open("/app/backend/routers/auth.py").read()
    assert '"created_at": created_at' in src
    assert '"created_at": created_at.isoformat()' in src


def test_chat_panel_mounts_founder_card_and_tint():
    src = open("/app/frontend/src/components/ChatPanel.jsx").read()
    assert "FounderOfferCard" in src
    assert "getChatBgTint" in src
    assert "founderTint" in src
