/**
 * server/aurem-db.js — SDK generated by AUREM CTO's Personal Track scaffolder.
 * Same design as the Python + Next.js clients: no raw Mongo credentials
 * baked into your app; everything routes through AUREM's managed REST
 * proxy.  Config via .env (dotenv):
 *   AUREM_API_BASE, AUREM_APP_ID, AUREM_APP_TOKEN
 */
const fetch = require("node-fetch");

class _Collection {
  constructor(client, name) { this.c = client; this.name = name; }
  async find(filter = {}, limit = 50, sort = null) {
    const r = await this.c._post(`${this.name}/find`, { filter, limit, sort });
    return (r && r.docs) || [];
  }
  async findOne(filter) {
    const r = await this.c._post(`${this.name}/find-one`, { filter });
    return r && r.doc;
  }
  async insert(data, schema = null) {
    return this.c._post(`${this.name}/insert`, { data, schema });
  }
  async update(filter, patch) {
    return this.c._request("PATCH", `${this.name}/update`, { filter, patch });
  }
  async delete(filter) {
    return this.c._request("DELETE", `${this.name}/delete`, { filter });
  }
}

class AuremDB {
  constructor() {
    this.base   = process.env.AUREM_API_BASE || "https://api.auremcto.com";
    this.appId  = process.env.AUREM_APP_ID;
    this.token  = process.env.AUREM_APP_TOKEN;
    if (!this.appId || !this.token) {
      throw new Error(
        "AUREM_APP_ID and AUREM_APP_TOKEN must be set. Run the materialize step " +
        "to have them injected into your .env.",
      );
    }
  }
  collection(name) { return new _Collection(this, name); }
  async _request(method, path, body = null) {
    const url = `${this.base}/api/managed-db/${this.appId}/${path}`;
    const r = await fetch(url, {
      method,
      headers: {
        "Authorization": `Bearer ${this.token}`,
        "Content-Type":  "application/json",
      },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!r.ok) {
      const text = await r.text().catch(() => "");
      throw new Error(`AUREM DB ${method} ${path} failed: ${r.status} ${text}`);
    }
    return r.json();
  }
  async _post(path, body) { return this._request("POST", path, body); }
}

module.exports = { AuremDB, db: new AuremDB() };
