"""
services/seo/image_alts.py — Add `alt` attributes to <img> tags
missing them. Alt text is generated by the project's standard LLM
(services/llm.py:call_llm) — NOT a direct vendor SDK — so the
emergent integrations billing + persona contract is honored.
"""
from __future__ import annotations

from typing import Optional

from bs4 import BeautifulSoup

from services.llm import call_llm

from .meta_tags import SeoPatch


_MAX_ALT_LEN = 125          # WCAG / Google recommendation
_LLM_MAX_TOKENS = 80
_FALLBACK_ALT_PREFIX = "image: "


async def _llm_alt_text(image_src: str, page_context: str) -> str:
    """Return an alt-text string for a single image. On any LLM
    failure we synthesise a fallback from the filename so the page
    still gets an `alt` attribute (WCAG compliance > perfect alt)."""
    try:
        prompt = (
            "Generate a concise, descriptive HTML alt text (≤125 chars).\n"
            f"Image src: {image_src}\n"
            f"Page context: {page_context or '(no context provided)'}\n"
            "Rules:\n"
            "- Be descriptive of the visible content.\n"
            "- No 'image of', 'picture of', 'photo of' prefix.\n"
            "- Lowercase first letter unless proper noun.\n"
            "- Return ONLY the alt text, no quotes, no commentary."
        )
        out = await call_llm(
            messages=[{"role": "user", "content": prompt}],
            system=(
                "You write SEO and WCAG-compliant alt text. "
                "Reply with a single short sentence."
            ),
            max_tokens=_LLM_MAX_TOKENS,
            temperature=0.4,
        )
        out = (out or "").strip().strip('"').strip("'")
        if len(out) > _MAX_ALT_LEN:
            out = out[: _MAX_ALT_LEN - 1].rstrip() + "…"
        return out or _fallback_from_src(image_src)
    except Exception:
        return _fallback_from_src(image_src)


def _fallback_from_src(src: str) -> str:
    """Cheap, deterministic fallback when the LLM is unavailable."""
    if not src:
        return _FALLBACK_ALT_PREFIX + "decorative"
    last = src.rsplit("/", 1)[-1]
    last = last.rsplit(".", 1)[0]
    last = last.replace("-", " ").replace("_", " ").strip()
    if not last:
        return _FALLBACK_ALT_PREFIX + "decorative"
    return f"{_FALLBACK_ALT_PREFIX}{last[:_MAX_ALT_LEN - len(_FALLBACK_ALT_PREFIX)]}"


def find_unalted_imgs(html: str) -> list[dict]:
    """Pure helper — list every <img> missing or empty `alt`."""
    soup = BeautifulSoup(html, "html.parser")
    out: list[dict] = []
    for img in soup.find_all("img"):
        alt = img.get("alt")
        if alt is None or str(alt).strip() == "":
            src = img.get("src") or ""
            # Skip purely decorative role="presentation" — those
            # MUST have alt="" deliberately and we shouldn't touch.
            if (img.get("role") or "").lower() == "presentation":
                continue
            out.append({"src": src})
    return out


async def patch_image_alts(
    *,
    path: str,
    html: str,
    page_context: str = "",
    alt_provider=None,
) -> Optional[SeoPatch]:
    """Inject `alt` attributes on every <img> that doesn't have one.

    `alt_provider` is a coroutine `(src, page_context) -> str` —
    defaults to `_llm_alt_text`. The test suite swaps it out for a
    deterministic stub so unit tests never hit the network.
    """
    soup = BeautifulSoup(html, "html.parser")
    targets = []
    for img in soup.find_all("img"):
        alt = img.get("alt")
        if alt is not None and str(alt).strip() != "":
            continue
        if (img.get("role") or "").lower() == "presentation":
            continue
        targets.append(img)

    if not targets:
        return None

    gen = alt_provider or _llm_alt_text
    n_added = 0
    for img in targets:
        src = img.get("src") or ""
        alt_text = await gen(src, page_context)
        img["alt"] = alt_text or _fallback_from_src(src)
        n_added += 1

    return SeoPatch(
        path=path,
        before=html,
        after=str(soup),
        action="modify",
        reason=f"added alt= on {n_added} image(s)",
    )
